version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: daily
    time: '03:00'
  open-pull-requests-limit: 10
- package-ecosystem: gradle
  directory: "/app"
  schedule:
    interval: daily
    time: '03:00'
  open-pull-requests-limit: 10
